image: uber/android-build-environment:latest

pipelines:
  branches:
    develop:
    - step:
        caches:
          - gradle
          - maven
        script:
          - unset ANDROID_NDK_HOME
          - mkdir "${ANDROID_HOME}/licenses" || true
          - echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > "${ANDROID_HOME}/licenses/android-sdk-license"
          - bash ./gradlew build